--- TABLA DEPARTAMENTOS
CREATE TABLE dept (
  deptno INTEGER,
  dname TEXT,
  loc TEXT,
  CONSTRAINT pk_dept PRIMARY KEY (deptno)
);

--- TABLA EMPLEADOS
CREATE TABLE emp (
  empno INTEGER,
  ename TEXT,
  job TEXT,
  mgr INTEGER,
  hireDATE DATE,
  sal INTEGER,
  comm INTEGER,
  deptno INTEGER,
  CONSTRAINT pk_emp PRIMARY KEY (empno),
  CONSTRAINT fk_mgr FOREIGN KEY (mgr) REFERENCES emp (empno),
  CONSTRAINT fk_deptno FOREIGN KEY (deptno) REFERENCES dept (deptno)
);

--- INSERTAR DATOS EN TABLA DEPARTAMENTOS
INSERT INTO dept (deptno, dname, loc) VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO dept (deptno, dname, loc) VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO dept (deptno, dname, loc) VALUES (30, 'SALES', 'CHICAGO');
INSERT INTO dept (deptno, dname, loc) VALUES (40, 'OPERATIONS', 'BOSTON');

--- INSERTAR DATOS EN TABLA EMPLEADOS
INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) SELECT 7839, 'KING', 'PRESIDENT', cast(null as INTEGER), to_DATE('17-11-1981','dd-mm-yyyy'), 5000, cast(null as INTEGER), 10 
INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) SELECT 7698, 'BLAKE', 'MANAGER', 7839, to_DATE('1-5-1981','dd-mm-yyyy'), 2850, cast(null as INTEGER), 30;
INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) SELECT 7782, 'CLARK', 'MANAGER', 7839, to_DATE('9-6-1981','dd-mm-yyyy'), 2450, cast(null as INTEGER), 10; 
INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) SELECT 7566, 'JONES', 'MANAGER', 7839, to_DATE('2-4-1981','dd-mm-yyyy'), 2975, cast(null as INTEGER), 20; 
INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) SELECT 7902, 'FORD', 'ANALYST', 7566, to_DATE('3-12-1981','dd-mm-yyyy'), 3000, cast(null as INTEGER), 20; 
INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) SELECT 7369, 'SMITH', 'CLERK', 7902, to_DATE('17-12-1980','dd-mm-yyyy'), 800, cast(null as INTEGER), 20;
INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) SELECT 7499, 'ALLEN', 'SALESMAN', 7698, to_DATE('20-2-1981','dd-mm-yyyy'), 1600, 300, 30;
INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) SELECT 7521, 'WARD', 'SALESMAN', 7698, to_DATE('22-2-1981','dd-mm-yyyy'), 1250, 500, 30 ;
INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) SELECT 7654, 'MARTIN', 'SALESMAN', 7698, to_DATE('28-9-1981','dd-mm-yyyy'), 1250, 1400, 30 ;
INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) SELECT 7844, 'TURNER', 'SALESMAN', 7698, to_DATE('8-9-1981','dd-mm-yyyy'), 1500, 0, 30 ;
INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) SELECT 7900, 'JAMES', 'CLERK', 7698, to_DATE('3-12-1981','dd-mm-yyyy'), 950, cast(null as INTEGER), 30 ;
INSERT INTO emp (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) SELECT 7934, 'MILLER', 'CLERK', 7782, to_DATE('23-1-1982','dd-mm-yyyy'), 1300, cast(null as INTEGER), 10 ;